config/routes.rb
Rails.application.routes.draw do
  root to: 'toppages#index'
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  resources :tasks
  
  get 'signup', to: 'users#new'
  resources :users, only: [:show, :new, :create, :edit, :update, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :user
  
  validates :content, presence: true, length: {maximum: 255}
  validates :status, presence: true, length: {maximum: 10}
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email.downcase! }
  validates :name, presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: { maximum: 255 },
                   format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                   uniqueness: { case_sensitive: false }
  has_secure_password
  
  has_many :tasks, dependent: :destroy
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
  include SessionsHelper
  
  private
  
  def require_user_logged_in
    unless logged_in?
      redirect_to login_url
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    name = params[:session][:name]
    email= params[:session][:email].downcase
    password = params[:session][:password]
    
    if login(name, email, password)
      flash[:success] = 'ログインに成功しました。'
      redirect_to root_url
    else
      flash[:danger] = 'ログインに失敗しました。'
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = 'ログアウトしました。'
    redirect_to root_url
  end
  
  def login(name, email, password)
    @user = User.find_by(name: name, email: email)
    if @user&&@user.authenticate(password)
      session[:user_id] = @user.id
      return true
    else
      return false
    end
  end
  
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :require_user_logged_in
  before_action :correct_user, only: [:show, :edit, :update, :destroy]
  
  def index
    @tasks = current_user.tasks.all.order(status: :desc).order(created_at: :desc).page(params[:page]).per(5)
  end
  
  def show
    
  end
  
  def new
    @task = current_user.tasks.build
  end
  
  def create
    @task = current_user.tasks.build(task_params)
    
    if @task.save
      flash[:success] = 'タスクの追加が完了しました。'
      redirect_to root_url
    else
      flash.now[:danger] = 'タスクの追加に失敗しました'
      render :new
    end
  end
  
  def edit
    
  end
  
  def update
    
    if @task.update(task_params)
      flash[:success] = 'タスクの変更が完了しました'
      redirect_back(fallback_location: root_path)
    else
      flash[:danger] = 'タスクの変更に失敗しました'
      render :edit
    end
  end
  
  def destroy
    
    @task.destroy
    
    flash[:success] = 'タスクを消去しました。'
    redirect_back(fallback_location: root_path)
  end
  
  private
  
  def set_task
    @task = Task.find(params[:id])
  end
  
   # Strong Parameter
  def task_params
    params.require(:task).permit(:content, :status)
  end
  
  def correct_user
    @task = current_user.tasks.find_by(id: params[:id])
    unless @task
      redirect_to root_url
    end
  end
  
end

app/controllers/toppages_controller.rb
class ToppagesController < ApplicationController
  def index
    if logged_in?
      @tasks = current_user.tasks.order('status DESC').order('created_at DESC').page(params[:page]).per(5)
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_user_logged_in, only: [:show]
  
  def show
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
      if @user.save
        flash[:success] = 'ユーザー登録が完了しました。'
        redirect_to @user
      else
        flash[:danger] = 'ユーザー登録に失敗しました。'
        render :new
      end
  end
  
  def edit
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:success] = 'ユーザー情報を更新しました。'
      redirect_to edit_user_path
    else
      flash[:danger] = 'ユーザー情報の更新に失敗しました。'
      render 'edit'
    end
  end
  
  def destroy
    @user = User.find(params[:id])
    @user.destroy
    flash[:success] = 'ユーザーを削除しました。'
    redirect_to root_url
  end
  
  private
  
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    if @current_user
      return @current_user
    else
      @current_user = User.find_by(id: session[:user_id])
      return @current_user
    end
  end
  
  def logged_in?
    if current_user
      return true
    else
      return false
    end
  end
end

app/helpers/toppages_helper.rb
module ToppagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div class = "alert alert-warning">
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash_tasks.html.erb
<% flash.each do |message_type, message| %>
  <div class = "alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/layouts/_navbar.html.erb
<header>
  <div class = "navbar navbar-inverse navbar-static-top">
    <div class = "container">
      <div class = "navbar-header">
        <button type = "button" class = "navbar-toggle collapsed" data-toggle= "collapse" data-target = "#bs-example" aria-expanded = "false">
          <span class = "sr-only">Toggle navigation</span>
          <span class = "icon-bar"></span>
          <span class = "icon-bar"></span>
          <span class = "icon-bar"></span>
        </button>
        <a class = "navbar-brand" href = "/">TaskList</a>
      </div>
      <div class = "collapse navbar-collapse" id = "bs-example-navbar-collapse-1">
        <ul class = "nav navbar-nav navbar-right">
          <% if logged_in? %>
            <li>
                <%= link_to '新規タスクの追加', new_task_path %>
            </li>
            <li class = "dropdown">
              <a href = "#" class = "dropdown-toggle" data-toggle = "dropdown" role = "button" aria-haspopup = "true" aria-expanded = "false">ユーザー<span class = "caret"></span></a>
              <ul class = "dropdown-menu">
                <li><%= link_to 'ユーザー情報', user_path(current_user) %></li>
                <li role = "separator" class = "divider"></li>
                <li><%= link_to 'Logout', logout_path, method: :delete %></li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to 'ユーザー登録', signup_path %></li>
            <li><%= link_to 'ログイン', login_path %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset = "utf-8">
    <meta http-equiv = "X-UA-Compatible" content = "IE=edge">
    <meta name = "viewport" content = "width=device-width, initial-scale=1">
    
    <title>KadaiTasklist</title>
    <%= csrf_meta_tags %>
    
    <link rel = "stylesheet" href = "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src = "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  </head>

  <body>
      <%= render 'layouts/navbar' %>
    
    <div class = "container">
      <%= render 'layouts/flash_tasks' %>
      
      <%= yield %>
    </div>
  </body>
</html>

app/views/tasks/_form.html.erb
<div class = "row">
  <div class = "col-xs-12 col-sm-offset-2 col-sm-8 col-lg-offset-3 col-lg-6">
    <%= form_for(@task) do |f| %>
      <% if @task.errors.any? %>
        <div class = "alert alert-warning">
          <ul>
            <% @task.errors.full_messages.each do |message| %>
            <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
    
    <div class = "form-group">
      <%= f.label :content, 'タスク' %>
      <%= f.text_field :content, class: 'form-control' %>
    </div>
    
    <div class = "form-group">  
      <%= f.label :status, '状態' %>
      <%= f.select :status, ['未実行', '完了済'], {}, class: 'form-control' %>
    </div>
      
      <%= f.submit '投稿', class: 'btn btn-primary' %>
    <% end %>
  </div>
</div>

app/views/tasks/_tasks.html.erb
<h1>タスク一覧</h1>

<% if tasks.any? %>
  <% tasks.each do |task| %>
    <%= form_for(task) do |f| %>
    <table class = "table table-striped table-condensed">
      <thead>
        <th width = "80"></th>
        <th width = "50">id</th>
        <th>内容</th>
        <th width = "150">状態</th>
        <th width = "80"></th>
      </thead>
      <tbody>
        <tr>
          <td class = "text-center" style = "vertical-align:middle"><%= link_to '消去', task, method: :delete, data: {confirm: 'タスクを削除してもよろしいですか？'}, class: "btn btn-danger btn-xs" %></td>
          <td style = "vertical-align:middle"><%= link_to task.id, task %></td>
          <td style = "vertical-align:middle"><%= task.content %></td>
          <td style = "vertical-align:middle">
            <div class = "form-inline">
              <%= f.select :status, ['未実行', '完了済'], {}, class: 'form-control' %>
            </div>
          </td>
          <td style = "vertical-align:middle">
            <%= f.submit '更新', class: 'btn btn-primary' %>
          </td>
        </tr>
      </tbody>
    </table>
    <% end %>
  <% end %>
      
  <div>
    <%= paginate tasks %>
  </div>

<% end %>

app/views/tasks/_tasks_not_done.html.erb
<h1>未実行タスク</h1>

<% if tasks_not_done.any? %>
  <% tasks_not_done.each do |task| %>
    <%= form_for(task) do |f| %>
    <table class = "table table-striped table-condensed">
      <thead>
        <th width = "80"></th>
        <th width = "50">id</th>
        <th>内容</th>
        <th width = "150">状態</th>
        <th width = "80"></th>
      </thead>
      <tbody>
        <tr>
          <td class = "text-center" style = "vertical-align:middle"><%= link_to '消去', task, method: :delete, data: {confirm: 'タスクを削除してもよろしいですか？'}, class: "btn btn-danger btn-xs" %></td>
          <td style = "vertical-align:middle"><%= link_to task.id, task %></td>
          <td style = "vertical-align:middle"><%= task.content %></td>
          <td style = "vertical-align:middle">
            <div class = "form-inline">
              <%= f.select :status, ['未実行', '完了済'], {}, class: 'form-control' %>
            </div>
          </td>
          <td style = "vertical-align:middle">
            <%= f.submit '更新', class: 'btn btn-primary' %>
          </td>
        </tr>
      </tbody>
    </table>
    <% end %>
  <% end %>
      
  <div>
    <%= paginate tasks_not_done %>
  </div>

<% end %>

app/views/tasks/edit.html.erb
<h1>タスク内容の変更</h1>

<%= render 'form', tasks: @tasks %>

app/views/tasks/index.html.erb
<h1>タスク一覧</h1>

<% if @tasks.any? %>
  <% @tasks.each do |task| %>
    <%= form_for(task) do |f| %>
    <table class = "table table-striped table-condensed">
      <thead>
        <th width = "80"></th>
        <th width = "50">id</th>
        <th>内容</th>
        <th width = "150">状態</th>
        <th width = "80"></th>
      </thead>
      <tbody>
      <tr>
        <td class = "text-center" style = "vertical-align:middle"><%= link_to '消去', task, method: :delete, data: {confirm: 'タスクを削除してもよろしいですか？'}, class: "btn btn-danger btn-xs" %></td>
        <td style = "vertical-align:middle"><%= link_to task.id, task %></td>
        <td style = "vertical-align:middle"><%= task.content %></td>
        <td style = "vertical-align:middle">
          <div class = "form-inline">
            <%= f.select :status, ['未実行', '完了済'], {}, class: 'form-control' %>
          </div>
        </td>
        <td style = "vertical-align:middle">
          <%= f.submit '更新', class: 'btn btn-primary' %>
        </td>
      </tr>
      </tbody>
    </table>
    <% end %>
  <% end %>
<div>
  <%= paginate @tasks %>
</div>

<% end %>

app/views/tasks/new.html.erb
<h1>タスクの新規作成</h1>

<%= render 'form', task: @task %>

<br>

app/views/tasks/show.html.erb
<h1>id: <%= @task.id %>の詳細</h1>

<table class = "table table-bordered table-striped">
  <tr>
    <th>id</th>
    <td><%= @task.id %></td>
  </tr>
  <tr>
    <th>タスク</th>
    <td><%= @task.content %></td>
  </tr>
  <tr>
    <th>タスク</th>
    <td><%= @task.status %></td>
  </tr>
</table>

<%= link_to 'タスクを編集する', edit_task_path(@task), class: 'btn btn-primary' %>
<%= link_to 'タスクを消去する', @task, method: :delete, data: {confirm: 'タスクを消去しますか？'}, class: 'btn btn-danger' %>

app/views/toppages/index.html.erb
<% if logged_in? %>

<%= render 'tasks/tasks', tasks: @tasks %>

<% else %>
<div class = "center jumbotron">
  <div class = "text-center">
    <h1>TaskList</h1>
    <%= link_to 'ユーザー登録', signup_path, class: 'btn btn-primary' %>
  </div>
</div>
<% end %>

app/views/users/edit.html.erb
<div class = "text-center">
  <h1>ユーザー情報の更新</h1>
</div>

<div class = "row">
  <div class = "col-md-6 col-md-offset-3">
    
    <%= form_for(@user) do |f| %>
      
      <%= render 'layouts/error_messages', model: f.object %>
        
        <div class = "form-group">
          <%= f.label :name, '名前(ニックネーム)' %>
          <%= f.text_field :name, class: 'form-control' %>
        </div>
        
        <div class = "form-group">
          <%= f.label :email, 'メールアドレス' %>
          <%= f.email_field :email, class: 'form-control' %>
        </div>
        
        <div class = "form-group">
          <%= f.label :password, 'パスワード' %>
          <%= f.password_field :password, class: 'form-control' %>
        </div>
        
        <div class = "form-group">
          <%= f.label :password_confirmation, 'パスワード(確認)' %>
          <%= f.password_field :password_confirmation, class: 'form-control' %>
        </div>
      
      <%= f.submit '登録', class: 'btn btn-primary btn-block' %>
    
    <% end %>
    
  </div>
</div>

app/views/users/new.html.erb
<div class = "text-center">
  <h1>ユーザー登録</h1>
</div>

<div class = "row">
  <div class = "col-md-6 col-md-offset-3">
    
    <%= form_for(@user) do |f| %>
      <%= render 'layouts/error_messages', model: f.object %>
      
      <div class = "form-group">
        <%= f.label :name, '名前(ニックネーム)' %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>
      
      <div class = "form-group">
        <%= f.label :email, 'メールアドレス' %>
        <%= f.email_field :email, class: 'form-control' %>
      </div>
      
      <div class = "form-group">
        <%= f.label :password, 'パスワード' %>
        <%= f.password_field :password, class: 'form-control' %>
      </div>
      
      <div class = "form-group">
        <%= f.label :password_confirmation, 'パスワード(確認)' %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>
      </div>
      
      <%= f.submit '登録', class: 'btn btn-primary btn-block' %>
      
    <% end %>
    
  </div>
</div>

app/views/users/show.html.erb
<div class = "text-center">
  <h1>ユーザー情報</h1>
</div>

<div class = "row">
  <div class = "col-md-6 col-md-offset-3">
    <table class = "table table-bordered">
      <tr>
        <th>名前(ニックネーム)</th>
        <td><%= @current_user.name %></td>
      </tr>
      <tr>
        <th>メールアドレス</th>
        <td><%= @current_user.email %></td>
      </tr>
    <table>
    
    <div class = "text-center">
    <%= link_to 'ユーザー情報の更新', edit_user_path, class: 'btn btn-primary' %>　　<%= link_to 'ユーザーの消去', @user, method: :delete, data: { confirm: '本当に削除しますか？' }, class: 'btn btn-danger' %>
    </div>
  </div>
</div>